### ISSUE TITLE
Problem when setting custom gps coordinates.

### ISSUE THREAD

**Issue by Epsilith** [shiftcodeYT/PokemonGoBot#3]
When setting custom gps coordinates it just returns:
`[18:01:11][18:01:11] Evolved 12537596703159610633 successfully for 0xp`
and just keeps doing that. When I delete the gps.txt it will still work.

**Comment by shiftcodeYT** [comment]
Thanks for notifying me. I already know why :P I'll fix it in a minute.

**Comment by shiftcodeYT** [comment]
Fixed in newest commit. Release in a minute.

**Comment by shiftcodeYT** [comment]
Fixed in release 1.2.1, thanks for notifying.
