### ISSUE TITLE
Dont Work

### ISSUE THREAD

**Issue by dm94** [shiftcodeYT/PokemonGoBot#4]
t makes me all the time "null reference - restarting"

**Comment by shiftcodeYT** [comment]
Use PokeBot2. this version is discontinued. https://github.com/shiftcodeYT/PokeBot2

**Comment by dm94** [comment]
i use pokebot 2

**Comment by shiftcodeYT** [comment]
why are you opening a issue here then

**Comment by shiftcodeYT** [comment]
also, please post you external.config, without username & password.

**Comment by dm94** [comment]
<appSettings>
  <add key="AuthType" value="Ptc" />  
  <add key="PtcUsername" value="" />  
  <add key="PtcPassword" value="" />  
  <add key="DefaultLatitude" value="4,04173556" />  
  <add key="DefaultLongitude" value="-3,683196" />  
  <add key="LevelOutput" value="time" />  
  <add key="LevelTimeInterval" value="60" />  
  <add key="RecycleItemsInterval" value="60" />  
  <add key="Language" value="english" />  
  <add key="TransferType" value="duplicate" />  
  <add key="TransferCPThreshold" value="0" />  
  <add key="EvolveAllGivenPokemons" value="true" />
  <add key="ClientSettingsProvider.ServiceUri" value="" />
</appSettings>

**Comment by dm94** [comment]
![2a97dde1418f05daeb5b942e9bf806fc](https://cloud.githubusercontent.com/assets/7419213/17056129/96c199a6-5011-11e6-815c-2e5bd3c5b1d3.png)

**Comment by shiftcodeYT** [comment]
Did you delete username & password because i told you to, or did you forget to insert them?

**Comment by dm94** [comment]
because you told me

**Comment by dm94** [comment]
I think it's because logue PTC does not work, because servers are heavily loaded

**Comment by shiftcodeYT** [comment]
then ptc is broken, thanks for reporting :)
Please open a issue "PTC isn't working" on the new repo for PokeBot2

**Comment by dm94** [comment]
ok
